/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neurotechnology_Library_NativeManager */

#ifndef _Included_com_neurotechnology_Library_NativeManager
#define _Included_com_neurotechnology_Library_NativeManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neurotechnology_Library_NativeManager
 * Method:    getProductNameN
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_neurotechnology_Library_NativeManager_getProductNameN
  (JNIEnv *, jclass);

/*
 * Class:     com_neurotechnology_Library_NativeManager
 * Method:    getVersionMajorN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_neurotechnology_Library_NativeManager_getVersionMajorN
  (JNIEnv *, jclass);

/*
 * Class:     com_neurotechnology_Library_NativeManager
 * Method:    getVersionMinorN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_neurotechnology_Library_NativeManager_getVersionMinorN
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
