/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neurotechnology_Nffv_NffvUser */

#ifndef _Included_com_neurotechnology_Nffv_NffvUser
#define _Included_com_neurotechnology_Nffv_NffvUser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neurotechnology_Nffv_NffvUser
 * Method:    getID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_neurotechnology_Nffv_NffvUser_getID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neurotechnology_Nffv_NffvUser
 * Method:    loadImage
 * Signature: (JLcom/neurotechnology/Nffv/NffvImage;)V
 */
JNIEXPORT void JNICALL Java_com_neurotechnology_Nffv_NffvUser_loadImage
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
